### ISSUE TITLE
Syntax error: Bad for loop variable when running the image-install.sh script.

### ISSUE THREAD

**Issue by vochong** [endeavouros-arm/image-install#9]
$ sudo ./install-image-V2.7.sh 
./install-image-V2.7.sh: 203: ./install-image-V2.7.sh: Syntax error: Bad for loop variable

$ uname -a
Linux picasso 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"

**Comment by endeavouros-arm** [comment]
Unfortunately, our installer is not agnostic.  The installer must be run on ArchLinux, or a derivative Archlinux distro as the installer uses pacman to complete the install.

You do not have to install Arch Linux per se.  You can go here 
https://endeavouros.com/latest-release/
and download the latest EndeavourOS x86_64 live ISO.  Then burn the ISO to a USB Thumb drive.
Insert the Thumb drive into a x86_64 machine and boot from the live ISO.
In the "Welcome" screen is a button for installing EndeavourOS ARM to either RPi 4b / 400 or Odroid N2.

This installs an image onto a provided micro SD or USB SSD storage device.
Next connect the micro SD or USB SSD to the RPi or Odroid and it will boot into the Calamares installer where you choose time zone, language, Desktop Environment / Window Manager, hostname. username, and other information.  When this is finished, reboot and you will be in your new EndeavourOS ARM install.

Visit the EndeavourOS forum for further details or questions.
https://forum.endeavouros.com/

Pudge

**Comment by vochong** [comment]
Sorry I just stupidly did not look at the script content.   I've been converted from Ubuntu to Archlinux (thanks to Manjaro) since 5 years ago.   However, I later jumped from Manjaro to EndeavourOS  completely.   EndeavourOS is the most awesome Linux distribution I've ever tried.    All my old laptops have a new speedy life thanks to EndeavourOS / XFCE.    This Ubuntu is just a machine at work.  My whole-hearted thanks to Pudge and the team!
